### ISSUE TITLE
Reverse proxy installed but still not working correctly (504 error)

### ISSUE THREAD

**Issue by menoudyann** [menoudyann/VIR1-CadavreXski#13]
Bonsoir @NicolasGlassey,

J'ai tenté de mettre en place mon reverse proxy pour qu'il écoute sur le port 80 et qu'il redirige en fonction soit à l'API soit au frontend. Après maintes recherches, je ne comprends toujours pas qu'elle est notre erreur dans ce que nous avons configuré. Je pense que nous sommes vraiment pas loin. Serait-ce possible de jeter un oeil et nous donnez une "piste" afin de pouvoir terminer ce travail en beauté d'ici la fin de la semaine COM ?

Voici le commit en question : (1d93fe0c29626f508dcdc07d6d10189fb6e35e96)

Merci d'avance et belle soirée!

**Comment by NicolasGlassey** [comment]
@menoudyann 

Bonjour Yann,

Je suis pour l'instant la tête dans mes évaluations aussi bien pour le CPNV que pour la HEIG-vd.

Mais je tenais à vous donner quelques pistes pour vous permettre d'avancer.

Vous semblez, comme à votre habitude ;), vouloir que tout marche d'un coup. Voici comme je procéderai:

En local
* déployer le conteneur nginx et y accéder via le port 80 (simple redirection). Si la page de Nginx s'affiche alors on continue.
* configurer nginx pour rediriger le flux de la route "/" sur mon front-end (front-end qui doit être déployé, sur le port de votre choix mais dont nginx doit être informé). Si ok on continue.
* configurer nginx pour rediriger le flux de la route "/api/v1/" sur mon back-end. Si c'est ok.

* [Doc Nginx pour la config du reverse proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)

Passez sur AWS

Note : seul le conteneur nginx est exposé et répond derrière le fqdn. Les ip privés sont connus du Nginx, mais ne sont du coup pas divulguées ni au client api, ni à votre front-end.

Dites-moi où vous en êtes dans ce processus.
